apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-api
  template:
    metadata:
      labels:
        app: mini-api
    spec:
      containers:
      - name: mini-api
        image: $CI_REGISTRY_IMAGE:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mini-api
spec:
  selector:
    app: mini-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
